FROM ubuntu:latest

MAINTAINER chet00175

RUN apt-get -y update

RUN apt-get install -y software-properties-common

RUN apt-add-repository ppa:ansible/ansible

RUN apt-get -y update

RUN apt-get install -y ansible

